// Generated by CoffeeScript 1.6.3
/* Configuration file - Set your session Variables here*/


(function() {
  exports.HOSTNAME = process.env.HOSTNAME || 'localhost';

  exports.PORT = process.env.PORT || '3000';

}).call(this);
