// Generated by CoffeeScript 1.6.3
/* serve - Serves a static directory*/


(function() {
  var app, cfg, directory, express;

  express = require('express');

  cfg = require('./cfg/config.js');

  app = express();

  app.use(express.favicon());

  /* Logic*/


  directory = process.argv[2] || __dirname + '/static';

  if (directory === '.') {
    directory = process.cwd();
  }

  app.use(express["static"](directory));

  console.log("Serving static files from '" + directory + "'");

  /* Start the App*/


  app.listen("" + cfg.PORT);

}).call(this);
