// Generated by CoffeeScript 1.6.3
(function() {
  var app, cfg, directory, express;

  express = require('express');

  cfg = require('./cfg/config.js');

  app = express();

  app.use(express.favicon());

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  app.set('views', __dirname + '/views');

  app.set('view engine', 'jade');

  app.use(app.router);

  /* Controllers*/


  /* Routes*/


  /* Logic*/


  directory = process.argv[2] || __dirname + '/static';

  app.use(express["static"](directory));

  console.log("Serving static files from '" + directory + "'");

  /* Start the App*/


  app.listen("" + cfg.PORT);

}).call(this);
